@extends('layouts.base')
@section('title')
    NAMIC-Carolinas - Unplugged Issue 1
@endsection
@section(('content'))
<div id="container">
    <div id="content" data-layout="twocolumn" data-index="23"><div id="grid" class="container_24"><div id="pageTitle" class="page-title">UNPLUGGED Issue 1.0</div><br class="page-title" /><div id="billboard" class="billboard-holder" style="display:none;"><div class="billboard empty" data-id="0" data-height="300"></div></div><div class="column container grid_24 alpha"><div class="column grid_7 alpha"><div class="block image" data-type="image" data-title="image" data-id="0">			<div align='left'>
                            <img src="{{asset('img/issue1/1473191_2172640_1379264140.jpg')}}" style='float:left;'  class='image ' /></div>
                    </div></div><div class="column grid_17 omega"><div class="block heading" data-type="heading" data-title="heading" data-id="1"><h1><div class='h1' style='text-align:left;'>President's Message<br>
                                WHERE DO DREAMS START?</div></h1></div><div class="block text" data-type="text" data-title="text" data-id="2"><div style="">Nearly every great accomplishment began as a wildly ambitious dream.&nbsp; It is with great pleasure that I announce the launch of NAMIC-Carolinas's Quarterly Newsletter “Unplugged”. First, let me take a moment to thank each and every member of this chapter for supporting us and attending the many signature programming events, such as Digital Media Summit, Lunch and Learn Series, Resume Clinics plus Career Empowerment to name a few.&nbsp; We look forward in continuing to do so as well as support and partner with other affinity groups like WICT Carolinas and BBEN.<br>
                            <br>
                            Many of you may not know but this is my second and last term as your president.&nbsp; It has been a humbling and rewarding experience for me to serve in this capacity.&nbsp; I have not met each and every one of you individually but know that the board and I always have you at the forefront as we look to to empower, educate and advocate on your behalf.<br>
                            <br>
                            NAMIC-Carolinas “Unplugged” Newsletter will allow you to know us the board and your committee representatives a little better.&nbsp; We also look forward to highlighting our expert leaders throughout the telecommunications industry.&nbsp;&nbsp; In this quarterly publication we showcase Timer Warner Cable Regional Vice President, Business Class Customer Service Charlon McIntosh, a recent NAMIC Luminary receipient.&nbsp; You will also see other topics of discussion and conversations of interest in our HR Hub, Mission Accomplished and Lean Conversation sections of the newsletter.<br>
                            <br>
                            Again on behalf of the board and NAMIC National, we appreciate you and look forward to your continued support, feedback and comments.&nbsp; Please stay tuned for upcoming events and if you have not already done so; like us on Facebook and LinkedIn plus follow us on Twitter and Instagram. Please checkout our website for additional information.<br>
                            <br>
                            - Garth David, NAMIC-Carolinas President</div></div></div></div><div class="column container grid_24"><div class="column container grid_24 alpha"><div class="column grid_7 alpha"><div class="block image" data-type="image" data-title="image" data-id="3">			<div align='left'>
                                <img src="{{asset('img/issue1/1473191_2172645_1379264141.jpg')}}" style='float:left;'  class='image ' /></div>
                        </div></div><div class="column grid_17 omega"><div class="block heading" data-type="heading" data-title="heading" data-id="4"><h1><div class='h1' style='text-align:left;'>Executive Spotlight<br>
                                    Charlon McIntosh&nbsp;</div></h1></div><div class="block text" data-type="text" data-title="text" data-id="5"><div style="">As Regional Vice President of Business Class Customer Service for TWC, Charlon McIntosh knows a thing or two about professional career growth.&nbsp; With&nbsp;a charismatic personality, she is valued for her experience and leadership skills.&nbsp; We caught up with Charlon to discuss her success and accomplishments and for advice for&nbsp;those aspiring to ascend in their careers.<br>
                                <br>
                                &nbsp;<b>NC: How would you define your brand?</b><br>
                                <br>
                                Charlon McIntosh: I think of myself as someone who is a good partner and collaborator who is able to build strong cross-functional relationships.&nbsp; I’m very results oriented and I like to get things done.&nbsp; I also think that my role as a mentor/coach is an important part of my personal brand.<br>
                                &nbsp;<br>
                                <b>NC: What person or situation has had the biggest impact on your career growth?</b><br>
                                <br>
                                Charlon McIntosh: I think it’s been several people. I’m very fortunate to have mentors who give me honest feedback and I’m able to share things with them openly and honestly.&nbsp;&nbsp; I’ve also had amazing bosses who have been great teachers and very supportive of me throughout my career<br>
                                &nbsp;<br>
                                <b>NC: How important has networking been for your brand, career, and personal growth?</b><br>
                                <br>
                                Charlon McIntosh: It’s been really important! Here’s an example: although I’ve been in the cable industry for many years, I was new to Time Warner Cable and I knew that it was essential to go out and join the local NAMIC chapter and other organizations, such as WICT, so I could get to know people broadly across the company. I love when I go to an event and I meet a person who is working on a project with me from another area or department. It gives me a chance to meet people face-to-face and make that connection. It’s really been a particularly useful tool for me to learn the company and meet colleagues<br>
                                &nbsp;<br>
                                <b>NC: What was the best advice you were given that you would like to pass on to someone else?</b><br>
                                <br>
                                Charlon McIntosh: Find work that you are passionate about and work hard to be good at it.</div></div></div></div><div class="column grid_24 alpha"><div class="block heading" data-type="heading" data-title="heading" data-id="6"><h1><div class='h1' style='text-align:center;'>Monthly Empowerment Pal</div></h1></div><div class="block text" data-type="text" data-title="text" data-id="7"><div style="text-align:center;">“Nothing happens until you decide.&nbsp; Make a decision and watch your life move forward.”&nbsp;<br>
                            – Oprah Winfrey</div></div><div class="block heading" data-type="heading" data-title="heading" data-id="8"><h1><div class='h1' style='text-align:left;'>HR HUB</div></h1></div><div class="block text" data-type="text" data-title="text" data-id="9"><div style="">Are you ready for a career change?&nbsp; Are you working towards your next promotion or actively searching for a new career that better suites you?&nbsp; We’re here to help!&nbsp; Serena Porter, Human Resources Generalist, has offered great tips that&nbsp;will&nbsp;assist you with accomplishing your next career goal.<br>
                            &nbsp;<br>
                            <b>NC: What is the most common mistake candidates make when applying for jobs?&nbsp;</b><br>
                            &nbsp;<br>
                            Serena Porter: One of the most common mistakes is submitting a resume that contains typos and/or grammatical errors.&nbsp; You can’t take back that first impression and those types of misses can label an applicant as having poor basic communication and writing skills.<br>
                            &nbsp;<br>
                            <b>NC: What do you look for in the first six seconds of reviewing a resume?&nbsp;</b><br>
                            &nbsp;<br>
                            Serena Porter: Candidates often present themselves via a resume that represents an entirely different ‘brand’ than the actual position for which they are applying.&nbsp; It is important to tailor your resume and objective to the specific position.&nbsp; Emphasize the information related to the job and make those six seconds count.<br>
                            &nbsp;<br>
                            <b>NC: What is your opinion on a candidate who sends a direct email to the hiring manager after applying for a job?</b><br>
                            &nbsp;<br>
                            Serena Porter:&nbsp; It depends.&nbsp; The hiring process can take some time.&nbsp; Being strategic and courteous while not being overly persistent about contacting the hiring team is a slippery slope.&nbsp; The recruiter and hiring manager may still be reviewing resumes and a good resume speaks for itself.&nbsp; If the hiring manager encouraged you to apply or if you have a networking connection to them, then following up a week or two later with an email is certainly appropriate.<br>
                            &nbsp;<br>
                            <b>NC: What advice would you offer to someone who was not chosen for a job that they feel they were qualified for?&nbsp;</b><br>
                            &nbsp;<br>
                            Serena Porter: Candidates may not immediately see the obvious challenges and opportunities that come with the position that another person may have been better suited for.&nbsp; If given the chance to receive feedback, keep an open mind as to what the recruiter or hiring manager had to say.&nbsp; It can offer you valuable insight into how to present yourself as the best candidate-additional training, education, or interviewing skills.</div></div><div class="block heading" data-type="heading" data-title="heading" data-id="10"><h1><div class='h1' style='text-align:left;'>MISSION ACCOMPLISHED</div></h1></div><div class="block text" data-type="text" data-title="text" data-id="11"><div style=""><b>Ronda Bryant<br>
                                Three years NAMIC-Carolinas member</b><br>
                            <br>
                            After receiving a Bachelor’s degree in Public Relations and Marketing, Ronda aspired to work in the Communications field.&nbsp; Starting her career in Customer Care and Operations for TWC, she immediately began networking with the Marking and Communications department by becoming a TWC Ambassador.&nbsp; She also jumped on the opportunity to network while advancing her Communications skills and joined NAMIC-Carolinas.&nbsp; Recently, Ronda accomplished her goal by accepting a position as a Communications Coordinator with Time Warner Cable.&nbsp; Her next goal is to create a five year developmental plan of advancement through the Communications department.<br>
                            <br>
                            <b>Brittany S. S.&nbsp;Hardin<br>
                                Four years NAMIC-Carolinas member</b><br>
                            <br>
                            Starting out as a 2008 STARS intern with Time Warner Cable, Brittany Hardin joined the company shortly after and became a Traffic Coordinator for Time Warner Cable Media.&nbsp; Brittany hit the ground running by joining NAMIC-Carolinas and WICT Carolinas and even participated on the charter and launch team for Time Warner Cable’s Black Business Employee Network.&nbsp; Brittany has now transitioned to Retail Sales Associate in Residential Sales and Marketing for Time Warner Cable.&nbsp; With her ambition and love for media and emerging technology, this dynamic young professional is sure to make a great ambassador for TWC in her new role.<br>
                            <br>
                            It is with pleasure that we congratulate our NAMIC-Carolinas Communication team members as they accomplish their goals by achieving new heights!</div></div><div class="block heading" data-type="heading" data-title="heading" data-id="12"><h1><div class='h1' style='text-align:left;'>INSTANT REPLAY</div></h1></div><div class="block image" data-type="image" data-title="image" data-id="13">			<div align='center'>
                            <img src="{{asset('img/issue1/1473191_2172658_1379264141.jpg')}}" align='center'  class='image ' /></div>
                    </div><div class="block text" data-type="text" data-title="text" data-id="14"><div style="">NAMIC-Carolinas offered guest a chance to network and learn during a 2013 Lunch and Learn hosted in Charlotte, North Carolina.&nbsp; Attendees received an opportunity to listen to Telecommunications leaders, Ninette Bowman (Commercial Director,PAC &amp; Staging -TWC), Ralena Rowe (Director, TAM Human Resources-TWC) and Ed Nasseri (Director, Field Sales-ESPN/Disney) speak on topics regarding career progression and the application process.&nbsp; “Today I learned to expect change.&nbsp; Sometimes you have to be uncomfortable in order to change," says NAMIC-Carolinas member Tyffani Thompson.&nbsp;<br><br>Lunch and Learns are held throughout North and South Carolina and cover a variety of topics regarding growth and empowerment.&nbsp; For more information about NAMIC-Carolinas Lunch and Learns, please visit our website at&nbsp;<a href="/home" target="_self" data-cke-saved-href="/home">www.namiccarolinas.com</a>.&nbsp;</div></div><div class="block heading" data-type="heading" data-title="heading" data-id="15"><h1><div class='h1' style='text-align:left;'>TECH TALK<br>
                                GOOGLE CHROMECAST</div></h1></div><div class="block image" data-type="image" data-title="image" data-id="16">			<div align='center'>
                            <img src="{{asset('img/issue1/1473191_2172656_1379264141.jpg')}}" align='center'  class='image ' /></div>
                    </div><div class="block text" data-type="text" data-title="text" data-id="17"><div style=""><b>What Is It?</b><br><br>Google Chromecast is a portable device that allows you to use Wi-Fi access to stream content from any mobile device (laptop, tablet or smartphone) to any HD or digital television with a HDMI port.<br>&nbsp;<br><b>What Does It Do?</b><br><br>After purchasing Google Chromecast for $35, you can download one of the four apps that partner with Google (Netflix, YouTube, Google Play and Google Chrome) on your&nbsp;Wi-Fi enabled&nbsp;device.&nbsp; Once you connect to Wi-Fi, you use Google Chromecast to seamlessly stream content like movies,&nbsp;personal videos and photos to your television.<br>&nbsp;<br><b>My Perspective….</b><br><br>Google has succeeded in making an inexpensive, user&nbsp;friendly streaming device that works with apps&nbsp;on&nbsp;Wi-Fi enabled devices.&nbsp; That means I can&nbsp;sit on my couch and stream my Netflix app from my iPhone&nbsp;to my TV and watch, “Orange is the New Black”.&nbsp;&nbsp;&nbsp;Advertisements&nbsp;on the YouTube app&nbsp;will be seen on the TV screen by a larger viewing audience.&nbsp;&nbsp; From a mobile advertising perspective, the potential revenue&nbsp;that can be generated from&nbsp;in-app advertising via a content provider’s partnership with&nbsp;Google's Chromecast would make me&nbsp;take a hard look at this platform.&nbsp;<br>&nbsp;<br><b>My Prediction…<br></b><ul><li>As more devices&nbsp;that compliment streaming are developed, there will be a demand for faster internet speeds and Wi-Fi, which will result in competitive pricing.&nbsp;</li><li>Mobile advertising will increase as advertisers become aware of consumer mobile&nbsp;habits</li><li>More developers (gaming, content providers, educators etc.) will create apps that take advantage of streaming and the ability to stream apps on a TV screen</li></ul></div></div><div class="block heading" data-type="heading" data-title="heading" data-id="18"><h1><div class='h1' style='text-align:left;'>NAMIC-Carolinas' Confessions</div></h1></div><div class="block text" data-type="text" data-title="text" data-id="19"><div style=""><b>Jihad Edwards<br>
                                Financial Analyst, Time Warner Cable</b><br>
                            Three years NAMIC-Carolinas member</div></div><div class="block videoplayer" data-type="videoplayer" data-title="videoplayer" data-id="20"><div style="text-align:center;" ><iframe src="//www.youtube.com/embed/fqBHX2k9YHk?rel=0?wmode=opaque" width="480" height="360" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div></div><div class="block heading" data-type="heading" data-title="heading" data-id="21"><h1><div class='h1' style='text-align:left;'>LEAN CONVERSATION</div></h1></div><div class="block text" data-type="text" data-title="text" data-id="22"><div style="">Working in a cubicle for 8 hours a day can have a negative impact on your health.&nbsp; Let us help you make it a positive one!&nbsp; Here are a few healthy eating tips to get you started.<br>
                            <br>
                            <b>Do not skip meals!</b><br>
                            <br>
                            Put the work down and save some pounds!&nbsp; Skipping meals is an unhealthy habit that will cause your body to release stress hormones that equate to fat.&nbsp; Be sure to take a break (thirty minutes to one hour) and enjoy a healthy meal.<br>
                            <br>
                            <b>Prepare your lunch at home!</b><br>
                            <br>
                            Are you guilty of buying your lunch every day?&nbsp; Try bringing your lunch to work for a change.&nbsp; Salads, fresh fruits, and vegetables are much healthier choices than fast food.&nbsp; Fast food is low in nutrients and high in fat and calories.&nbsp; By preparing your meals at home you can save money and eat healthier!<br>
                            <br>
                            <b>Opt for healthy snacks!</b><br>
                            <br>
                            Would you like a leaner abdomen?&nbsp; Eat blueberries!&nbsp; The sweet and tangy fruit helps to rid fat around the waistline.&nbsp; &nbsp;Not only will blueberries help shed pounds but they are also low in calories and offer the recommended dose of fiber and vitamin C. &nbsp;<br>
                            <br>
                            <a href="http://www.fitneass.com/office-healthy-tips/" target="_blank">http://www.fitneass.com/office-healthy-tips/</a><br>
                            <a href="http://www.mdhil.com/10-health-tips-office/" target="_blank">http://www.mdhil.com/10-health-tips-office/</a></div></div></div></div><div style="clear:both;"></div></div></div>	</div>
@endsection